name: generate snake animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {}

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Move output into repo root and commit to main
        run: |
          cp dist/github-contribution-grid-snake.svg ./github-contribution-grid-snake.svg
          cp dist/github-contribution-grid-snake-dark.svg ./github-contribution-grid-snake-dark.svg
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add github-contribution-grid-snake.svg github-contribution-grid-snake-dark.svg
          git commit -m "chore: update snake animation" || echo "No changes to commit"
          git push
